# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InputTester.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='InputTester.proto',
  package='test.SortingAlgorithm',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11InputTester.proto\x12\x15test.SortingAlgorithm\"r\n\tInputTest\x12\x41\n\x10sortingAlgorithm\x18\x01 \x01(\x0e\x32\'.test.SortingAlgorithm.SortingAlgorithm\x12\x0e\n\x06is_asc\x18\x02 \x01(\x08\x12\x12\n\ninput_list\x18\x03 \x03(\x05*R\n\x10SortingAlgorithm\x12\x0e\n\nBUBBLESORT\x10\x00\x12\x0c\n\x08HEAPSORT\x10\x01\x12\x11\n\rINSERTIONSORT\x10\x02\x12\r\n\tMERGESORT\x10\x03\x62\x06proto3'
)

_SORTINGALGORITHM = _descriptor.EnumDescriptor(
  name='SortingAlgorithm',
  full_name='test.SortingAlgorithm.SortingAlgorithm',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='BUBBLESORT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HEAPSORT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INSERTIONSORT', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MERGESORT', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=160,
  serialized_end=242,
)
_sym_db.RegisterEnumDescriptor(_SORTINGALGORITHM)

SortingAlgorithm = enum_type_wrapper.EnumTypeWrapper(_SORTINGALGORITHM)
BUBBLESORT = 0
HEAPSORT = 1
INSERTIONSORT = 2
MERGESORT = 3



_INPUTTEST = _descriptor.Descriptor(
  name='InputTest',
  full_name='test.SortingAlgorithm.InputTest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sortingAlgorithm', full_name='test.SortingAlgorithm.InputTest.sortingAlgorithm', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_asc', full_name='test.SortingAlgorithm.InputTest.is_asc', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='input_list', full_name='test.SortingAlgorithm.InputTest.input_list', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=158,
)

_INPUTTEST.fields_by_name['sortingAlgorithm'].enum_type = _SORTINGALGORITHM
DESCRIPTOR.message_types_by_name['InputTest'] = _INPUTTEST
DESCRIPTOR.enum_types_by_name['SortingAlgorithm'] = _SORTINGALGORITHM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputTest = _reflection.GeneratedProtocolMessageType('InputTest', (_message.Message,), {
  'DESCRIPTOR' : _INPUTTEST,
  '__module__' : 'InputTester_pb2'
  # @@protoc_insertion_point(class_scope:test.SortingAlgorithm.InputTest)
  })
_sym_db.RegisterMessage(InputTest)


# @@protoc_insertion_point(module_scope)
